inherit_gem:
  rubocop-discourse: default.yml

Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false

Discourse/TimeEqMatcher:
  Enabled: false

AllCops:
  Exclude:
    - 'gems/**/*'
    - 'vendor/**/*'

RSpec/NamedSubject:
  Enabled: false
